#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Minimal Artisan (fixture for integration testing)
|--------------------------------------------------------------------------
*/

echo "Laravel Framework 10.48.22\n";
